//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WellTrajectoryCalculator.rc
//
#define IDC_CLIPBOOK                    3
#define IDR_2D_DESIGN                   3
#define IDC_ADD_TO_CLIPBOOK             4
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_2DDIALOG                    102
#define IDC_NOACTION                    103
#define IDD_3DWOptDlg                   112
#define IDD_ConstraintsDlg              113
#define IDR_MAINFRAME                   128
#define IDD_3D_LOCATOR                  130
#define IDD_2D_CLIPBOOK                 131
#define IDD_NEW_CLIPBOOK_REC            132
#define IDD_2_CIRC_ARC_SEG_OPTIONS      137
#define IDD_2D_TRAJECTORY               139
#define IDB_EXTENDED_J_TRAJECTORY       142
#define IDB_J_TRAJECTORY                143
#define IDB_EXTENDED_S_TRAJECTORY       144
#define IDB_S_TRAJECTORY                145
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_DISPLAY                     1001
#define IDC_EDIT3                       1002
#define IDC_EDIT4                       1003
#define IDC_TARGETS                     1003
#define IDC_EDIT5                       1004
#define IDC_EDIT6                       1005
#define IDC_EDIT7                       1006
#define IDC_EDIT8                       1007
#define IDC_LABEL_BR_2                  1008
#define IDC_TVD                         1009
#define IDC_Sensitivity                 1010
#define IDC_RESTORE                     1010
#define IDC_CHECK1                      1011
#define IDC_LIST                        1011
#define IDC_CHECK2                      1012
#define IDC_NAME                        1012
#define IDC_CHECK3                      1013
#define IDC_Inclination                 1014
#define IDC_CHECK4                      1014
#define IDC_Azimuth                     1015
#define IDC_CHECK5                      1015
#define IDC_CHECK6                      1016
#define IDC_CHECK7                      1017
#define IDC_CHECK8                      1018
#define IDC_Apply                       1019
#define IDC_Disp                        1020
#define IDC_EDIT1Units                  1021
#define IDC_Isotropic                   1022
#define IDC_BUTTON1                     1023
#define IDC_BUTTON2                     1024
#define IDC_BUTTON3                     1025
#define IDC_BUTTON4                     1026
#define IDC_BUTTON5                     1027
#define IDC_BUTTON6                     1028
#define IDC_BUTTON7                     1029
#define IDC_BUTTON8                     1030
#define IDC_EDIT2Units                  1031
#define IDC_EDIT3Units                  1032
#define IDC_EDIT4Units                  1033
#define IDC_EDIT5Units                  1034
#define IDC_EDIT6Units                  1035
#define IDC_EDIT7Units                  1036
#define IDC_EDIT8Units                  1037
#define IDC_TVDUnits                    1038
#define IDC_DispUnits                   1039
#define IDC_RADIO1                      1040
#define IDC_RADIO2                      1041
#define IDC_RADIO3                      1042
#define IDC_RADIO4                      1043
#define IDC_RADIO5                      1044
#define IDC_RADIO6                      1045
#define IDC_RADIO7                      1046
#define IDC_RADIO8                      1047
#define IDC_RADIO9                      1048
#define IDC_RADIO10                     1049
#define IDC_RADIO11                     1050
#define IDC_RADIO12                     1051
#define IDC_InclinationUnits            1056
#define IDC_AzimuthUnits                1057
#define IDC_Length                      1058
#define IDC_LengthUnits                 1059
#define IDC_BuildRate1                  1060
#define IDC_BuildRate1Units             1061
#define IDC_TRY                         1062
#define IDC_BTN_ARC_BR1                 1063
#define IDC_BuildRate2                  1064
#define IDC_BuildRate2Units             1065
#define IDC_BTN_ARC_BR2                 1066
#define IDC_AddItem                     1068
#define IDC_Length2                     1069
#define IDC_LengthUnits2                1070
#define IDC_RemoveItem                  1071
#define IDC_WND_POS                     1076
#define IDC_Go                          1077
#define IDC_Step                        1078
#define IDC_SLIDER1                     1079
#define IDC_Find                        1080
#define IDC_SPREAD1                     1082
#define IDC_SPIN1                       1083
#define IDC_SPIN2                       1084
#define IDC_SPIN3                       1085
#define IDC_SPIN4                       1086
#define IDC_SPIN5                       1087
#define IDC_SPIN6                       1088
#define IDC_SPIN7                       1089
#define IDC_SPIN8                       1090
#define IDC_TRAJECTORY_VIEW             1091
#define IDC_Help                        1349
#define IDM_S_TRAJ                      40800
#define IDM_EXT_S_TRAJ                  40801
#define IDM_J_TRAJ                      40802
#define IDM_EXT_J_TRAJ                  40803

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         40804
#define _APS_NEXT_CONTROL_VALUE         1092
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
